#!/bin/bash

updatequotes() {
uri=$(curl -s "https://api.quotable.io/random?maxLength=26")

echo $uri | jq '.content' |  cut -d "\"" -f 2 > "$HOME/.cache/eww.quote.x"
echo $uri | jq '.author' |  cut -d "\"" -f 2 > "$HOME/.cache/eww.author.y"
}

quote=$(cat $HOME/.cache/eww.quote.x)
author=$(cat $HOME/.cache/eww.author.y)

if [ "$quote" = "" ] ; then
	quote="Bad programmers worry about the code."
    author="Linus Torvalds"
fi

case $1 in
quote)
echo $quote
;;
author)
echo "- $author"
;;
update)
  updatequotes
;;
esac
